/**
 * Creating a sidebar enables you to:
 * - create an ordered group of docs
 * - render a sidebar for each doc of that group
 * - provide next/previous navigation
 *
 * The sidebars can be generated from the filesystem, or explicitly defined here.
 *
 * Create as many sidebars as you want.
 */

// @ts-check

/** @type { import('@docusaurus/plugin-content-docs').SidebarsConfig } */
const sidebars = {
  tutorialSidebar: [{"type": "autogenerated", "dirName": "."}],
    tutorialSidebar: [
    [{'type': 'category', 'label': 'architecture_1', 'items': ['architecture_1/architecture']}, {'type': 'category', 'label': 'device-management_1', 'items': ['device-management_1/device-management']}, {'type': 'category', 'label': 'join-rdk_1', 'items': ['join-rdk_1/join-rdk']}, {'type': 'category', 'label': 'rdk-camera-documentation_1', 'items': ['rdk-camera-documentation_1/rdk-camera-documentation']}, {'type': 'category', 'label': 'rdk-camera-architecture', 'items': ['rdk-camera-documentation_1/rdk-camera-architecture/rdk-camera-architecture']}]
  ],
};

export default sidebars;
